package com.minh.order_service.enums;

public enum SagaStep {
    STARTED,
    PRODUCT_RESERVING,
    PRODUCT_RESERVED,
    PAYMENT_PROCESSING,
    PAYMENT_PROCESSED,
    ORDER_COMPLETED,
    // Compensating steps
    PRODUCT_RELEASING,
    PRODUCT_RELEASED,
    PAYMENT_REFUNDED,
    PRODUCT_RESERVATION_FAILED,
    PRODUCT_RESERVED_CONFIRMING,
    PRODUCT_RESERVED_CONFIRMED,
    ORDER_CANCELLING, PAYMENT_REFUNDING, ORDER_CREATED, ORDER_COMPLETION_FAILED, PAYMENT_FAILED, COMPENSATED
}