server:
  port: 8080
spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/}
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: api-documentation
          uri: lb://bff
          predicates:
            - Path=/api-docs/**,/v3/api-docs/**
            - Method=GET,POST,PUT,DELETE,PATCH

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/api/products,/api/categories/**,/api/categories
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: CircuitBreaker
              args:
                name: productService
                fallbackUri: "forward:/products/contact-support"

        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/carts/**,/api/carts,/api/files/**,/api/files,/api/reviews/**,/api/reviews,/api/users/**,/api/addresses/**,/api/users,/api/addresses
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: CircuitBreaker
              args:
                name: cartService
                fallbackUri: "forward:/support/contact-support"

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**,/api/orders,/api/promotions/**,/api/promotions
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: "forward:/orders/contact-support"

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**,/api/payments,/api/payment-methods/**,/api/payment-methods
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: CircuitBreaker
              args:
                name: paymentService
                fallbackUri: "forward:/payments/contact-support"

        - id: notify-service
          uri: lb://notify-service
          predicates:
            - Path=/api/templates/**,/api/templates,/api/send-logs,/api/send-logs/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: CircuitBreaker
              args:
                name: notifyService
                fallbackUri: "forward:/notify/contact-support"

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/games/**,/api/games,/api/campaigns,/api/campaigns/**,/api/questions/**,/api/questions,/api/vouchers/**,/api/vouchers,/api/question-collections/**,/api/question-collections,/api/events/**,/api/events
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: CircuitBreaker
              args:
                name: gameService
                fallbackUri: "forward:/events/contact-support"
        - id: ws-event
          uri: lb:ws://realtime-gateway
          predicates:
            - Path=/ws/events/**,/ws/events,/events/**,/events
          filters:
            - StripPrefix=0
      httpclient:
        connect-timeout: 10000
        response-timeout: 20s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI:http://localhost:9090/realms/e-commerce/protocol/openid-connect/certs}

management:
  metrics:
    distribution:
      percentiles-histogram:
        resilience4j:
          circuitbreaker:
            enabled: true
        http:
          server:
          requests:
            enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    loggers:
      access: unrestricted
    beans:
      cache:
        time-to-live: 10s
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    # Liveness and Readiness probes configuration.
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    circuitbreakers:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
      preferIpAddress: true
    register-with-eureka: true
    fetch-registry: true



# Resilience configuration
resilience4j:
  timelimiter:
    instances:
      productService:
        timeoutDuration: 15s
      cartService:
        timeoutDuration: 15s
      orderService:
        timeoutDuration: 15s
      paymentService:
        timeoutDuration: 15s
      promotionService:
        timeoutDuration: 15s
      fileService:
        timeoutDuration: 15s
      userService:
        timeoutDuration: 15s
      review-service:
        timeoutDuration: 15s

  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10 # Số lượng cuộc gọi được theo dõi. 10 cuộc gọi gần nhất.
        minimum-number-of-calls: 10 # Số lượng yêu cầu tối thiểu để Circuit breaker bắt đầu tính tỷ lệ fail.
        permittedNumberOfCallsInHalfOpenState: 3  # Số lượng cuộc gọi được phép thực hiện khi Circuit breaker ở trạng thái Half-Open. Nếu vượt quá số này, Circuit breaker sẽ chuyển sang trạng thái Open nếu tỷ lệ lỗi vượt quá ngưỡng.
        automaticTransitionFromOpenToHalfOpenEnabled: true # Cho phép tự động chuyển từ trạng thái Open sang Half-Open sau một khoảng thời gian nhất định.
        waitDurationInOpenState: 10000 # Khoảng thời gian (tính bằng milliseconds) mà Circuit breaker sẽ ở trạng thái Open trước khi tự động chuyển sang Half-Open để kiểm tra xem dịch vụ đã ổn định trở lại hay chưa.
        failureRateThreshold: 70  # Ngưỡng tỷ lệ lỗi (tính bằng phần trăm) mà nếu vượt quá, Circuit breaker sẽ chuyển sang trạng thái Open. Ví dụ: nếu 70% số cuộc gọi thất bại, Circuit breaker sẽ mở và ngăn chặn các cuộc gọi tiếp theo đến dịch vụ cho đến khi nó được kiểm tra lại.

      cartService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 70
      orderService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 70
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 70
      promotionService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 70
      fileService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 70
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 70
      reviewService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 70