CREATE DATABASE IF NOT EXISTS ecommerce_product;
CREATE DATABASE IF NOT EXISTS ecommerce_order;
CREATE DATABASE IF NOT EXISTS ecommerce_payment;
CREATE DATABASE IF NOT EXISTS ecommerce_game;
CREATE DATABASE IF NOT EXISTS ecommerce_notify;
CREATE DATABASE IF NOT EXISTS ecommerce_cart;